apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - namespace.yaml
images:
  - name: wireguard-cni
    newName: ghcr.io/unstoppablemango/wireguard-cni
    newTag: "0.0.1"
