apiVersion: v1
kind: ConfigMap
metadata:
  name: wireguard-cni-config
  namespace: wireguard-cni
data:
  10-wireguard.conflist: |
    {
      "cniVersion": "1.0.0",
      "name": "wireguard",
      "plugins": [
        {
          "type": "wireguard-cni",
          "address": "10.100.0.1/24",
          "privateKey": "REPLACE_WITH_WG_PRIVATE_KEY",
          "peers": []
        }
      ]
    }
